#################################################
##### BACKBONE MINIGAME CONFIGURATION FILE ######
#################################################
# Please do not change ANYTHING in this file! ###
# This file contains important information which#
# keeps your awesome pvp games running smoothly.#
################################################# 
# If anything in this file is changed, you may ##
# experience severe issues in-game. UNLESS you ##
# know what you're doing, DO NOT TOUCH THIS FILE#
#################################################
# BACKBONE, the BACKBONE LOGO, and all other    #
# refrences to BACKBONE belong to it's creator  #
################  FIREBREATH15  #################